# Generated by Django 4.0.5 on 2022-06-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='choice',
            field=models.CharField(choices=[('грн', 'грн'), ('евр', 'евро'), ('дол', 'доллары')], default='грн', max_length=3),
        ),
    ]
